### ISSUE TITLE
prestashop 1.55 -->parseerror in mpay24.php

### ISSUE THREAD

**Issue by acreifi** [sadrian/mpay24_prestashop#2]
i have downloaded the modul yesterday and tried to test the modul in prestashop 1.55.
the module does not  initialize. 

mpay24 (Parser-Fehler in /modules/mpay24/mpay24.php)
mpay24 (Klasse fehlt in /modules/mpay24/mpay24.php)

**Comment by sadrian** [comment]
Hello,

thanks for your meessage. Could you please provide a concrete error message from your web server logs?

However, I' afraid, that the failure is due to incompatibility with your version, which is not really up to date (from 2013). 

best regards
